### ISSUE TITLE
Fieldset CSS nests down to grandchildren

### ISSUE THREAD

**Issue by paul-vd** [geist-org/react#583]
# Bug report 🐞

The [css on the fieldset](https://github.com/geist-org/react/blob/74e76adbcf97f0ce76bbb3d3e382be52fdf3cfdb/components/fieldset/fieldset-content.tsx#L31-L37) causes the styles to nest down to all `last` and `first` children and their grandchildren.

## screenshots
> Before removing those nested values my custom components title is miss placed

![image](https://user-images.githubusercontent.com/39598117/125210853-da90f380-e291-11eb-9ab3-21308385326b.png)

> When I comment out those nested styling to the title is correctly placed

![image](https://user-images.githubusercontent.com/39598117/125210878-f98f8580-e291-11eb-988f-852400596b49.png)

> You will notice the `Equipment` title is now in its correct position.

![image](https://user-images.githubusercontent.com/39598117/125210964-67d44800-e292-11eb-8883-246b657874e0.png)

I would suggest changing it to direct children only.
```css
    .content :global(>:first-child) {
      margin-top: 0;
    }
    .content :global(>:last-child) {
      margin-bottom: 0;
    }
```
